### PR TITLE
Homepage Changed

### PR DESCRIPTION
**Pull request by Dhruvrode**
Description:

1)Added A slide show of images for UI improvements.
It is automatic and also contain indicators !
when you hove on indicator the color changes

2)Added an animation to logo and text of header.
whenever  your load the page it will show first icon then the Excoders .

That all from my side.

### CODE REVIEW

**Comment by rahulkamilya** [comment]
I apriciarate your dedication and hardwork @Dhruvrode 

But, I don't  have pictures for add right now, logo animation is Perfect 🏷️
please remove  "slide show of images" 

then I'II marge it as hackoctobarfst-accepted

**Comment by Dhruvrode** [comment]
Ok i will do it @rahulkamilya  no worries !

**Comment by Dhruvrode** [comment]
Hey @rahulkamilya  i have made neccessary changes! 
You check latest commit or i should make a new for the same please tell.
Tell me if you need any other changes :) ,I would be happy to help!
Looking forward to contribute more on this repo.

**Comment by rahulkamilya** [comment]
@Dhruvrode Make another Pull request, There is a problem on Conflicting files

**Pull request closed without merging**
